name: Debian packaging

on:
  [ push, pull_request ]

jobs:
  debian_publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies ğŸ“¦
        run: sudo apt-get update && sudo apt-get install -y dh-python build-essential devscripts fakeroot debhelper python3-all python3-setuptools
      - uses: actions/setup-python@v3
        name: setup Python
        with:
          python-version: '3.10'
      - name: Checkout pywis-pubsub
        uses: actions/checkout@master
      - name: build Debian package ğŸ—ï¸
        run: sudo debuild -b -uc -us
